### ISSUE TITLE
MBDyn for windows

### ISSUE THREAD

**Issue by Kishoret99** [gdbaldw/BlenderAndMBDyn#25]
Hi sir,
I am Kishore. Thanks very much for the addon. I am planning to do a college project on Suspension and Steering Design of Remote controlled Vehicles. I think that  Blender's IK and this addon is sufficiently enough for my work. What I came to know is that I have to install MBDyn for the actual process to work on. I am currently on Windows 8.1 and tried to compile the source code in cygwin by following instructions from random sites (I am totally very new all this source code stuff and compilation ) by downloading the zip, I got errors in the process, I don't know what the errors actually mean. I would like to know whether MBDyn works on windows. If not how can I proceed further. If possible can you instruct us in the installation procedure/tutorial on windows . I have researched myself in the net but nothing is there I can find, so  I am asking you as a final.Links to downlaod the .exe file will be great if possible. Please help me in this issue, It would be very much help to my project. Thank you.

**Comment by gdbaldw** [comment]
First, Blender IK is not used by BlenderAndMBDyn. Any Blender IK will be independent of any MBDyn modeling and simulation. Regarding Windows and using MBDyn, I suggest you browse the mbdyn.org user mailing list archive ( https://lists.mbdyn.org/pipermail/mbdyn-users/ ), and if this does not fully answer your questions pose them on that list.-Doug  On 04/17/16, Kishoret99notifications@github.com wrote: Hi sir,I am Kishore. Thanks very much for the addon. I am planning to do a college project on Suspension and Steering Design of Remote controlled Vehicles. I think that  Blender's IK and this addon is sufficiently enough for my work. What I came to know is that I have to install MBDyn for the actual process to work on. I am currently on Windows 8.1 and tried to compile the source code in cygwin by following instructions from random sites (I am totally very new all this source code stuff and compilation ) by downloading the zip, I got errors in the process, I don't know what the errors actually mean. I would like to know whether MBDyn works on windows. If not how can I proceed further. If possible can you instruct us in the installation procedure/tutorial on windows . I have researched myself in the net but nothing is there I can find, so  I am asking you as a final.Links to downlaod the .exe file will be great if possible. Please help me in this issue, It would be very much help to my proje ct. Thank you.—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by louisgag** [comment]
Kishore, you can get MBDyn precompiled for Windows here: 
http://www.aero.polimi.it/masarati/Download/mbdyn/mbdyn-1.7.0-win32.zip
Be aware that the Windows version of MBDyn has some limitations (such as 
sockets).
-Louis

On 17-Apr-2016 05:03 PM, gdbaldw wrote:

>  First, Blender IK is not used by BlenderAndMBDyn. Any Blender IK will 
> be independent of any MBDyn modeling and simulation. Regarding Windows 
> and using MBDyn, I suggest you browse the mbdyn.org user mailing list 
> archive ( https://lists.mbdyn.org/pipermail/mbdyn-users/ ), and if 
> this does not fully answer your questions pose them on that 
> list.-Doug  On 04/17/16, Kishoret99notifications@github.com 
> wrote: Hi sir,I am Kishore. Thanks very much for the addon. I am 
> planning to do a college project on Suspension and Steering Design of 
> Remote controlled Vehicles. I think that Blender's IK and this addon 
> is sufficiently enough for my work. What I came to know is that I have 
> to install MBDyn for the actual process to work on. I am currently on 
> Windows 8.1 and tried to compile the source code in cygwin by 
> following instructions from random sites (I am totally very new all 
> this source code stuff and compilation ) by downloading the zip, I got 
> errors in the process, I don't know what the errors actually mean. I 
> would like to know whether MBDyn works on windows. If not how can I 
> proceed further. If possible can you instruct us in the installation 
> procedure/tutorial on windows . I have researched myself in the net 
> but nothing is there I can find, so I am asking you as a final.Links 
> to downlaod the .exe file will be great if possible. Please help me in 
> this issue, It would be very much help to my proje ct. Thank you.—You 
> are receiving this because you are subscribed to this thread.Reply to 
> this email directly or view it on GitHub
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/gdbaldw/BlenderAndMBDyn/issues/25#issuecomment-211040685

## 

Louis Gagnon, Ph.D.
Postdoctoral fellow
Dipartimento di Scienze e Tecnologie Aerospaziali
Politecnico di Milano
http://louisgagnon.com/research/

**Comment by Kishoret99** [comment]
Sir, Thank you very much for the link, that is exactly what I am looking for the past few days. As said by you, in windows I have problems in animating the results, although the results are created succesfully in a folder. Is there anything I could install/modify to solve this error. When I went through the MBDyn forum, I found one of the member  posted  https://lists.mbdyn.org/pipermail/mbdyn-users/2015-December/001679.html some code there, Is that a solution? And If it is a solution, how to proceed further after downloading the .cpp code. Sorry if these questions annoy you, basically I am a noob in computer architecture, so I am asking these questions. Any help will be great. Thanks again for the link. 

cpp code

[attachment1.txt](https://github.com/gdbaldw/BlenderAndMBDyn/files/223824/attachment1.txt)

**Comment by gdbaldw** [comment]
As far as I know, sockets is still not implemented in MBDyn for Windows. The BlenderAndMBDyn limitation is that animation is not realtime in Windows, but you may after the fact import the motion data to animate the objects. The other potential limitation with Windows is that plotting requires installation of Pandas for Windows, and which may not be correctly configured by default.  On 04/18/16, Kishoret99notifications@github.com wrote: Sir, Thank you very much for the link, that is exactly what I am looking for the past few days. As said by you, in windows I have problems in animating the results, although the results are created succesfully in a folder. Is there anything I could install/modify to solve this error. When I went through the MBDyn forum, I found one of the member  posted  https://lists.mbdyn.org/pipermail/mbdyn-users/2015-December/001679.html some code there, Is that a solution? And If it is a solution, how to proceed further after downloading the .cpp code. Sorry if these questions annoy you, basically I am a noob in computer architecture, so I am asking these questions. Any help will be great. Thanks again for the link. cpp codeattachment1.txt—You are receiving this because you commented.Reply to this email directly or view it on GitHub

**Comment by Kishoret99** [comment]
Ok sir, I will think of other options like installing ubuntu. Thanks for the help and the answers. And one general question, I will do my research but any good recommendation for plotting graphs for blender as my project needs to output as graphs.Anything like addon or external program that can talk with blender preferably in real time.

**Comment by gdbaldw** [comment]
Yes, in Ubuntu you may install Pandas3 for plotting. By the way, you can also Google for a nightly build of Blender for Ubuntu, which is more current than the version provided by the Ubuntu Software Center.-Doug  On 04/20/16, Kishoret99notifications@github.com wrote: Ok sir, I will think of other options like installing ubuntu. Thanks for the help and the answers. And one general question, I will do my research but any good recommendation for plotting graphs for blender as my project needs to output as graphs.Anything like addon or external program that can talk with blender preferably in real time. —You are receiving this because you commented.Reply to this email directly or view it on GitHub
